### PR TITLE
Update parts.gohtml

### PR DESCRIPTION
**Pull request by RatchetOfVaporex**
Updated Parts.gohtml, (#143)

### CODE REVIEW

**Comment by jacksonargo** [comment]
:thinking: seems weird that the tests aren't running... once sec.

**Comment by 0az** [comment]
Might be something with approval timing.

**Comment by jacksonargo** [comment]
@RatchetOfVaporex can you clone from this repo and push or do you not have perms?

**Comment by 0az** [comment]
Closing in favor of #145

**Pull request closed without merging**
