### PR TITLE
Envconfig + Tokens!

### PR DESCRIPTION
**Pull request by jacksonargo**
I added some to code to generate tokens, altho nothing uses it yet.

But, we can take tokens in an http headers, and prep rep, members, and admin have different api's they can hit.
Members is still http basic auth, and is still used for the views.
Prep rep is a token used with vvgo-uploader
Admin right now just protects the debug endpoints.

### CODE REVIEW

**Comment by jacksonargo** [comment]
Because I didn't think about that! lmao I'll use bearer auth header.

**Comment by jacksonargo** [comment]
I'm reading up on BearerAuth and this looks like some OAuth stuff. I honestly don't know anything about OAuth, so that's why I using an app specific header.

As far as implementing something that can be used with OAuth, are these tokens like `196ddf804c7666d4-8d32ff4a91a530bc-c5c7cde4a26096ad-67758135226bfb2e` valid OAuth tokens?

**Comment by jacksonargo** [comment]
Ah yeah just what we need! https://pkg.go.dev/golang.org/x/oauth2?tab=doc

**Comment by jacksonargo** [comment]
I do want to implement Oauth, but can we save it for later?
For now, we'll use the same http header, since these aren't oauth tokens yet.

**Comment by 0az** [comment]
I use the "Bearer" terminology in the generic sense: we can use Bearer tokens without OAuth.

In this case, it'd just be checking against a token whitelist.

**Comment by jacksonargo** [comment]
Oh, maybe I don't understand then. What is the http header you are suggesting?

**Comment by 0az** [comment]
Example: `Authorization: Bearer b3141414e578ccb1`

**Comment by jacksonargo** [comment]
Updated to use the bearer header.
```
Authorization: Bearer 196ddf804c7666d4-8d32ff4a91a530bc-c5c7cde4a26096ad-67758135226bfb2e
```

**Pull request merged**
